name: simple workflow

# Déclencheurs
on:
  #schedule:
    #- cron: "0 * * * *"   # Toutes les heures pile (UTC)
  workflow_dispatch:       # Exécution manuelle

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Message 1
        run: echo "Récupération du code source"

      - name: Message 2
        run: echo "Vérification terminée"
